#!/usr/bin/env ruby

# use ruby to get relative paths
require 'pathname'

Dir['.[a-z]*'].each do |file|
  next if file == '.git'
  path = Pathname.new(Dir.pwd + '/' + file)
  home = Pathname.new(ENV['HOME'])
  rel  = path.relative_path_from home
  link = ENV['HOME'] + '/' + file
  puts "#{link} -> #{rel}"
  system "rm -f #{link} && ln -s #{rel} #{link}"
end
